"""add currency to derived monetary records

Revision ID: 849be651d3d6
Revises: cdfe87bb63c7
Create Date: 2026-08-31 19:42:09.183623
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '849be651d3d6'
down_revision: Union[str, Sequence[str], None] = 'cdfe87bb63c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_relationships', sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False))
    op.add_column('cash_position_snapshots', sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False))
    op.add_column('evidence_edges', sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False))
    op.add_column('exceptions', sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False))
    op.add_column('follow_up_tasks', sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False))
    op.add_column('reconciliation_cases', sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reconciliation_cases', 'currency')
    op.drop_column('follow_up_tasks', 'currency')
    op.drop_column('exceptions', 'currency')
    op.drop_column('evidence_edges', 'currency')
    op.drop_column('cash_position_snapshots', 'currency')
    op.drop_column('candidate_relationships', 'currency')
    # ### end Alembic commands ###
