"""create phase 3 persistence schema

Revision ID: cdfe87bb63c7
Revises: 
Create Date: 2026-08-31 18:38:32.943909
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'cdfe87bb63c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_up_tasks',
    sa.Column('case_id', sa.Text(), nullable=False),
    sa.Column('task_type', sa.Text(), nullable=False),
    sa.Column('amount_at_risk_paise', sa.BigInteger(), nullable=False),
    sa.Column('required_evidence', sa.Text(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('action_code', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='OPEN', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_follow_up_tasks_case_id', 'follow_up_tasks', ['case_id'], unique=False)
    op.create_index('ix_follow_up_tasks_status', 'follow_up_tasks', ['status'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('request_checksum', sa.Text(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'idempotency_key')
    )
    op.create_index('ix_idempotency_created_at', 'idempotency_records', ['created_at'], unique=False)
    op.create_table('policy_versions',
    sa.Column('policy_id', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('policy_checksum', sa.Text(), nullable=False),
    sa.Column('policy_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'version')
    )
    op.create_table('reconciliation_runs',
    sa.Column('status', sa.Text(), server_default='CREATED', nullable=False),
    sa.Column('policy_version_id', sa.UUID(), nullable=True),
    sa.Column('dataset_checksum', sa.Text(), nullable=True),
    sa.Column('rule_set_version', sa.Text(), nullable=True),
    sa.Column('app_version', sa.Text(), nullable=True),
    sa.Column('ai_model', sa.Text(), nullable=True),
    sa.Column('ai_prompt_version', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('cash_position', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('evaluation', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('result_checksum', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('total_source_rows', sa.Integer(), nullable=True),
    sa.Column('total_cases', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_analyses',
    sa.Column('reconciliation_run_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.Text(), nullable=False),
    sa.Column('evidence_packet', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_model', sa.Text(), nullable=True),
    sa.Column('ai_prompt_version', sa.Text(), nullable=True),
    sa.Column('tokens_prompt', sa.Integer(), nullable=True),
    sa.Column('tokens_completion', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('validation_passed', sa.Boolean(), nullable=True),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['reconciliation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_analyses_case_id', 'ai_analyses', ['case_id'], unique=False)
    op.create_index('ix_ai_analyses_run_id', 'ai_analyses', ['reconciliation_run_id'], unique=False)
    op.create_table('candidate_relationships',
    sa.Column('reconciliation_run_id', sa.UUID(), nullable=False),
    sa.Column('source_entity_id', sa.Text(), nullable=False),
    sa.Column('target_entity_id', sa.Text(), nullable=False),
    sa.Column('relationship_type', sa.Text(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('decision_level', sa.Text(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('evidence_fields', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('allocated_amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('rule_id', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['reconciliation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candidates_run_id', 'candidate_relationships', ['reconciliation_run_id'], unique=False)
    op.create_index('ix_candidates_source', 'candidate_relationships', ['source_entity_id'], unique=False)
    op.create_index('ix_candidates_target', 'candidate_relationships', ['target_entity_id'], unique=False)
    op.create_table('cash_position_snapshots',
    sa.Column('reconciliation_run_id', sa.UUID(), nullable=False),
    sa.Column('bank_confirmed_paise', sa.BigInteger(), nullable=False),
    sa.Column('settlement_confirmed_in_transit_paise', sa.BigInteger(), nullable=False),
    sa.Column('expected_settlement_paise', sa.BigInteger(), nullable=False),
    sa.Column('at_risk_paise', sa.BigInteger(), nullable=False),
    sa.Column('unresolved_paise', sa.BigInteger(), nullable=False),
    sa.Column('scheduled_refunds_paise', sa.BigInteger(), nullable=False),
    sa.Column('known_disputes_paise', sa.BigInteger(), nullable=False),
    sa.Column('known_reserve_holds_paise', sa.BigInteger(), nullable=False),
    sa.Column('safe_cash_paise', sa.BigInteger(), nullable=False),
    sa.Column('buckets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['reconciliation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reconciliation_run_id')
    )
    op.create_index('ix_cash_position_run_id', 'cash_position_snapshots', ['reconciliation_run_id'], unique=False)
    op.create_table('evidence_edges',
    sa.Column('reconciliation_run_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.Text(), nullable=False),
    sa.Column('source_entity_id', sa.Text(), nullable=False),
    sa.Column('target_entity_id', sa.Text(), nullable=False),
    sa.Column('relationship_type', sa.Text(), nullable=False),
    sa.Column('allocated_amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('rule_id', sa.Text(), nullable=False),
    sa.Column('rule_version', sa.Text(), nullable=False),
    sa.Column('evidence_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision_level', sa.Text(), nullable=False),
    sa.Column('actor_type', sa.Text(), server_default='SYSTEM', nullable=False),
    sa.Column('verification_checks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['reconciliation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reconciliation_run_id', 'source_entity_id', 'target_entity_id', 'relationship_type', 'rule_id')
    )
    op.create_index('ix_evidence_case_id', 'evidence_edges', ['case_id'], unique=False)
    op.create_index('ix_evidence_run_id', 'evidence_edges', ['reconciliation_run_id'], unique=False)
    op.create_index('ix_evidence_source', 'evidence_edges', ['source_entity_id'], unique=False)
    op.create_index('ix_evidence_target', 'evidence_edges', ['target_entity_id'], unique=False)
    op.create_table('exceptions',
    sa.Column('reconciliation_run_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.Text(), nullable=False),
    sa.Column('exception_code', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('amount_at_risk_paise', sa.BigInteger(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('checks_passed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checks_failed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missing_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('owner_role', sa.Text(), nullable=True),
    sa.Column('ai_assisted', sa.Boolean(), nullable=False),
    sa.Column('human_review_state', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['reconciliation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reconciliation_run_id', 'case_id', 'exception_code')
    )
    op.create_index('ix_exceptions_case_id', 'exceptions', ['case_id'], unique=False)
    op.create_index('ix_exceptions_code', 'exceptions', ['exception_code'], unique=False)
    op.create_index('ix_exceptions_run_id', 'exceptions', ['reconciliation_run_id'], unique=False)
    op.create_table('human_decisions',
    sa.Column('case_id', sa.Text(), nullable=False),
    sa.Column('reconciliation_run_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('previous_state', sa.Text(), nullable=False),
    sa.Column('new_state', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('invariant_passed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['reconciliation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_human_decisions_case_id', 'human_decisions', ['case_id'], unique=False)
    op.create_index('ix_human_decisions_created_at', 'human_decisions', ['created_at'], unique=False)
    op.create_index('ix_human_decisions_run_id', 'human_decisions', ['reconciliation_run_id'], unique=False)
    op.create_table('invariant_results',
    sa.Column('reconciliation_run_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.Text(), nullable=False),
    sa.Column('invariant_id', sa.Text(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('expected_value', sa.Text(), nullable=True),
    sa.Column('actual_value', sa.Text(), nullable=True),
    sa.Column('affected_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['reconciliation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reconciliation_run_id', 'case_id', 'invariant_id')
    )
    op.create_index('ix_invariants_case_id', 'invariant_results', ['case_id'], unique=False)
    op.create_index('ix_invariants_run_id', 'invariant_results', ['reconciliation_run_id'], unique=False)
    op.create_table('reconciliation_cases',
    sa.Column('case_id', sa.Text(), nullable=False),
    sa.Column('reconciliation_run_id', sa.UUID(), nullable=False),
    sa.Column('case_state', sa.Text(), nullable=False),
    sa.Column('decision_level', sa.Text(), nullable=True),
    sa.Column('gross_amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('net_amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('residual_paise', sa.BigInteger(), nullable=False),
    sa.Column('exception_code', sa.Text(), nullable=True),
    sa.Column('exception_severity', sa.Text(), nullable=True),
    sa.Column('amount_at_risk_paise', sa.BigInteger(), nullable=False),
    sa.Column('cash_bucket', sa.Text(), nullable=True),
    sa.Column('settlement_id', sa.Text(), nullable=True),
    sa.Column('bank_receipt_state', sa.Text(), nullable=True),
    sa.Column('owner_role', sa.Text(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('ai_assisted', sa.Boolean(), nullable=False),
    sa.Column('human_reviewed', sa.Boolean(), nullable=False),
    sa.Column('source_entity_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('record_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['reconciliation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'reconciliation_run_id')
    )
    op.create_index('ix_cases_case_id', 'reconciliation_cases', ['case_id'], unique=False)
    op.create_index('ix_cases_created_at', 'reconciliation_cases', ['created_at'], unique=False)
    op.create_index('ix_cases_exception_code', 'reconciliation_cases', ['exception_code'], unique=False)
    op.create_index('ix_cases_owner_role', 'reconciliation_cases', ['owner_role'], unique=False)
    op.create_index('ix_cases_run_id', 'reconciliation_cases', ['reconciliation_run_id'], unique=False)
    op.create_index('ix_cases_state', 'reconciliation_cases', ['case_state'], unique=False)
    op.create_table('source_files',
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('file_checksum', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('ingestion_quality', sa.Text(), nullable=False),
    sa.Column('reconciliation_run_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['reconciliation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reconciliation_run_id', 'source_type')
    )
    op.create_index('ix_source_files_checksum', 'source_files', ['file_checksum'], unique=False)
    op.create_index('ix_source_files_created_at', 'source_files', ['created_at'], unique=False)
    op.create_index('ix_source_files_run_id', 'source_files', ['reconciliation_run_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('reconciliation_run_id', sa.UUID(), nullable=True),
    sa.Column('case_id', sa.Text(), nullable=True),
    sa.Column('source_file_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=True),
    sa.Column('rule_id', sa.Text(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actor', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['reconciliation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_case_id', 'audit_events', ['case_id'], unique=False)
    op.create_index('ix_audit_events_created_at', 'audit_events', ['created_at'], unique=False)
    op.create_index('ix_audit_events_event_type', 'audit_events', ['event_type'], unique=False)
    op.create_index('ix_audit_events_run_id', 'audit_events', ['reconciliation_run_id'], unique=False)
    op.create_table('raw_source_rows',
    sa.Column('source_file_id', sa.UUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality', sa.Text(), nullable=False),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_file_id', 'row_number')
    )
    op.create_index('ix_raw_source_rows_created_at', 'raw_source_rows', ['created_at'], unique=False)
    op.create_index('ix_raw_source_rows_file_id', 'raw_source_rows', ['source_file_id'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('bank_transaction_id', sa.Text(), nullable=False),
    sa.Column('merchant_id', sa.Text(), nullable=False),
    sa.Column('account_id', sa.Text(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('narration', sa.Text(), nullable=False),
    sa.Column('utr', sa.Text(), nullable=True),
    sa.Column('raw_row_id', sa.UUID(), nullable=False),
    sa.Column('reconciliation_run_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("direction IN ('CREDIT', 'DEBIT')", name='ck_bank_direction'),
    sa.ForeignKeyConstraint(['raw_row_id'], ['raw_source_rows.id'], ),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['reconciliation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_transaction_id', 'merchant_id', 'reconciliation_run_id')
    )
    op.create_index('ix_bank_transactions_id', 'bank_transactions', ['bank_transaction_id'], unique=False)
    op.create_index('ix_bank_transactions_posted_at', 'bank_transactions', ['posted_at'], unique=False)
    op.create_index('ix_bank_transactions_run_id', 'bank_transactions', ['reconciliation_run_id'], unique=False)
    op.create_index('ix_bank_transactions_utr', 'bank_transactions', ['utr'], unique=False)
    op.create_table('ingestion_issues',
    sa.Column('source_file_id', sa.UUID(), nullable=True),
    sa.Column('raw_row_id', sa.UUID(), nullable=True),
    sa.Column('field_name', sa.Text(), nullable=True),
    sa.Column('issue_type', sa.Text(), nullable=False),
    sa.Column('rejected_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_row_id'], ['raw_source_rows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_issues_file_id', 'ingestion_issues', ['source_file_id'], unique=False)
    op.create_index('ix_ingestion_issues_raw_row_id', 'ingestion_issues', ['raw_row_id'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.Text(), nullable=False),
    sa.Column('merchant_id', sa.Text(), nullable=False),
    sa.Column('order_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('expected_payment_status', sa.Text(), nullable=True),
    sa.Column('raw_row_id', sa.UUID(), nullable=False),
    sa.Column('reconciliation_run_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_row_id'], ['raw_source_rows.id'], ),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['reconciliation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'merchant_id', 'reconciliation_run_id')
    )
    op.create_index('ix_orders_created_at', 'orders', ['order_created_at'], unique=False)
    op.create_index('ix_orders_merchant_id', 'orders', ['merchant_id'], unique=False)
    op.create_index('ix_orders_order_id', 'orders', ['order_id'], unique=False)
    op.create_index('ix_orders_run_id', 'orders', ['reconciliation_run_id'], unique=False)
    op.create_table('payments',
    sa.Column('payment_id', sa.Text(), nullable=False),
    sa.Column('merchant_id', sa.Text(), nullable=False),
    sa.Column('order_id', sa.Text(), nullable=False),
    sa.Column('payment_status', sa.Text(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_method', sa.Text(), nullable=True),
    sa.Column('gateway_reference', sa.Text(), nullable=True),
    sa.Column('raw_row_id', sa.UUID(), nullable=False),
    sa.Column('reconciliation_run_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_row_id'], ['raw_source_rows.id'], ),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['reconciliation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id', 'merchant_id', 'reconciliation_run_id')
    )
    op.create_index('ix_payments_captured_at', 'payments', ['captured_at'], unique=False)
    op.create_index('ix_payments_order_id', 'payments', ['order_id'], unique=False)
    op.create_index('ix_payments_payment_id', 'payments', ['payment_id'], unique=False)
    op.create_index('ix_payments_run_id', 'payments', ['reconciliation_run_id'], unique=False)
    op.create_table('settlement_components',
    sa.Column('component_id', sa.Text(), nullable=False),
    sa.Column('settlement_id', sa.Text(), nullable=False),
    sa.Column('component_type', sa.Text(), nullable=False),
    sa.Column('source_event_id', sa.Text(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('raw_row_id', sa.UUID(), nullable=False),
    sa.Column('reconciliation_run_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("direction IN ('CREDIT', 'DEBIT')", name='ck_component_direction'),
    sa.ForeignKeyConstraint(['raw_row_id'], ['raw_source_rows.id'], ),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['reconciliation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id', 'reconciliation_run_id')
    )
    op.create_index('ix_components_component_id', 'settlement_components', ['component_id'], unique=False)
    op.create_index('ix_components_run_id', 'settlement_components', ['reconciliation_run_id'], unique=False)
    op.create_index('ix_components_settlement_id', 'settlement_components', ['settlement_id'], unique=False)
    op.create_index('ix_components_source_event_id', 'settlement_components', ['source_event_id'], unique=False)
    op.create_table('settlements',
    sa.Column('settlement_id', sa.Text(), nullable=False),
    sa.Column('merchant_id', sa.Text(), nullable=False),
    sa.Column('settlement_status', sa.Text(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('net_amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_bank_date', sa.Date(), nullable=True),
    sa.Column('utr', sa.Text(), nullable=True),
    sa.Column('raw_row_id', sa.UUID(), nullable=False),
    sa.Column('reconciliation_run_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_row_id'], ['raw_source_rows.id'], ),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['reconciliation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('settlement_id', 'merchant_id', 'reconciliation_run_id')
    )
    op.create_index('ix_settlements_initiated_at', 'settlements', ['initiated_at'], unique=False)
    op.create_index('ix_settlements_run_id', 'settlements', ['reconciliation_run_id'], unique=False)
    op.create_index('ix_settlements_settlement_id', 'settlements', ['settlement_id'], unique=False)
    op.create_index('ix_settlements_utr', 'settlements', ['utr'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_settlements_utr', table_name='settlements')
    op.drop_index('ix_settlements_settlement_id', table_name='settlements')
    op.drop_index('ix_settlements_run_id', table_name='settlements')
    op.drop_index('ix_settlements_initiated_at', table_name='settlements')
    op.drop_table('settlements')
    op.drop_index('ix_components_source_event_id', table_name='settlement_components')
    op.drop_index('ix_components_settlement_id', table_name='settlement_components')
    op.drop_index('ix_components_run_id', table_name='settlement_components')
    op.drop_index('ix_components_component_id', table_name='settlement_components')
    op.drop_table('settlement_components')
    op.drop_index('ix_payments_run_id', table_name='payments')
    op.drop_index('ix_payments_payment_id', table_name='payments')
    op.drop_index('ix_payments_order_id', table_name='payments')
    op.drop_index('ix_payments_captured_at', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_orders_run_id', table_name='orders')
    op.drop_index('ix_orders_order_id', table_name='orders')
    op.drop_index('ix_orders_merchant_id', table_name='orders')
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_ingestion_issues_raw_row_id', table_name='ingestion_issues')
    op.drop_index('ix_ingestion_issues_file_id', table_name='ingestion_issues')
    op.drop_table('ingestion_issues')
    op.drop_index('ix_bank_transactions_utr', table_name='bank_transactions')
    op.drop_index('ix_bank_transactions_run_id', table_name='bank_transactions')
    op.drop_index('ix_bank_transactions_posted_at', table_name='bank_transactions')
    op.drop_index('ix_bank_transactions_id', table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index('ix_raw_source_rows_file_id', table_name='raw_source_rows')
    op.drop_index('ix_raw_source_rows_created_at', table_name='raw_source_rows')
    op.drop_table('raw_source_rows')
    op.drop_index('ix_audit_events_run_id', table_name='audit_events')
    op.drop_index('ix_audit_events_event_type', table_name='audit_events')
    op.drop_index('ix_audit_events_created_at', table_name='audit_events')
    op.drop_index('ix_audit_events_case_id', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_source_files_run_id', table_name='source_files')
    op.drop_index('ix_source_files_created_at', table_name='source_files')
    op.drop_index('ix_source_files_checksum', table_name='source_files')
    op.drop_table('source_files')
    op.drop_index('ix_cases_state', table_name='reconciliation_cases')
    op.drop_index('ix_cases_run_id', table_name='reconciliation_cases')
    op.drop_index('ix_cases_owner_role', table_name='reconciliation_cases')
    op.drop_index('ix_cases_exception_code', table_name='reconciliation_cases')
    op.drop_index('ix_cases_created_at', table_name='reconciliation_cases')
    op.drop_index('ix_cases_case_id', table_name='reconciliation_cases')
    op.drop_table('reconciliation_cases')
    op.drop_index('ix_invariants_run_id', table_name='invariant_results')
    op.drop_index('ix_invariants_case_id', table_name='invariant_results')
    op.drop_table('invariant_results')
    op.drop_index('ix_human_decisions_run_id', table_name='human_decisions')
    op.drop_index('ix_human_decisions_created_at', table_name='human_decisions')
    op.drop_index('ix_human_decisions_case_id', table_name='human_decisions')
    op.drop_table('human_decisions')
    op.drop_index('ix_exceptions_run_id', table_name='exceptions')
    op.drop_index('ix_exceptions_code', table_name='exceptions')
    op.drop_index('ix_exceptions_case_id', table_name='exceptions')
    op.drop_table('exceptions')
    op.drop_index('ix_evidence_target', table_name='evidence_edges')
    op.drop_index('ix_evidence_source', table_name='evidence_edges')
    op.drop_index('ix_evidence_run_id', table_name='evidence_edges')
    op.drop_index('ix_evidence_case_id', table_name='evidence_edges')
    op.drop_table('evidence_edges')
    op.drop_index('ix_cash_position_run_id', table_name='cash_position_snapshots')
    op.drop_table('cash_position_snapshots')
    op.drop_index('ix_candidates_target', table_name='candidate_relationships')
    op.drop_index('ix_candidates_source', table_name='candidate_relationships')
    op.drop_index('ix_candidates_run_id', table_name='candidate_relationships')
    op.drop_table('candidate_relationships')
    op.drop_index('ix_ai_analyses_run_id', table_name='ai_analyses')
    op.drop_index('ix_ai_analyses_case_id', table_name='ai_analyses')
    op.drop_table('ai_analyses')
    op.drop_table('reconciliation_runs')
    op.drop_table('policy_versions')
    op.drop_index('ix_idempotency_created_at', table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_index('ix_follow_up_tasks_status', table_name='follow_up_tasks')
    op.drop_index('ix_follow_up_tasks_case_id', table_name='follow_up_tasks')
    op.drop_table('follow_up_tasks')
    # ### end Alembic commands ###
