"""Render the submission metrics snapshot exclusively from measured artifacts."""

from __future__ import annotations

import json

from packages.domain.enums import CaseState
from scripts.benchmark_common import ROOT, format_inr, source_files
from services.normalization.policy import load_policy
from services.reconciliation.orchestrator import run_reconciliation


def main() -> None:
    evaluation = json.loads((ROOT / "out" / "evaluation.json").read_text())
    prediction = json.loads((ROOT / "out" / "reconciliation_report.json").read_text())
    manifest = json.loads((ROOT / "data" / "demo" / "dataset_manifest.json").read_text())
    stress = json.loads((ROOT / "out" / "stress_report.json").read_text())
    ablation = json.loads((ROOT / "out" / "ablation_report.json").read_text())
    aggregate = evaluation["aggregate"]
    ai_mode = next(item for item in ablation["modes"] if item["mode"] == "deterministic_plus_ai")

    policy = load_policy(ROOT / "policies" / "settlement_policy.v1.json")
    result = run_reconciliation(
        source_files(ROOT / "data" / "demo"),
        policy,
        "final-metrics",
    )
    amount_reconciled = sum(
        case.net_amount_paise
        for case in result.cases
        if case.case_state == CaseState.RECONCILED
    )

    rows = [
        ("Economic cases", str(manifest["total_cases"])),
        ("Source records", str(manifest["total_source_records"])),
        ("Verified match precision", f"{aggregate['relationship_precision']:.4f}"),
        ("Relationship recall", f"{aggregate['relationship_recall']:.4f}"),
        ("F1 score", f"{aggregate['relationship_f1']:.4f}"),
        ("Straight-through processing", f"{aggregate['stp_rate'] * 100:.1f}%"),
        ("Amount reconciled", format_inr(amount_reconciled)),
        (
            "Amount in transit",
            format_inr(result.cash_position.settlement_confirmed_in_transit_paise),
        ),
        ("Amount at risk", format_inr(result.cash_position.at_risk_paise)),
        ("Unexplained residual", format_inr(aggregate["unexplained_residual_paise"])),
        ("Open exception residual", format_inr(aggregate["open_exception_residual_paise"])),
        ("False positive count", str(aggregate["false_positive_count"])),
        ("End-to-end time (excl. AI)", f"{prediction['duration_seconds']:.6f} seconds"),
        ("AI-assisted cases", str(ai_mode["ai_assisted_cases"])),
        ("AI calls", str(ai_mode["ai_calls"])),
        ("Estimated AI cost", f"${ai_mode['ai_cost_usd']:.6f}"),
        ("Stress: records/second", f"{stress['records_per_second']:.2f}"),
    ]
    lines = [
        "# ClearLedger - Final Measured Results",
        "",
        f"Dataset: `{evaluation['dataset_id']}`. All values are generated by `make verify-claims`.",
        "",
        "| Metric | Value |",
        "|---|---:|",
        *[f"| {label} | {value} |" for label, value in rows],
        "",
        "AI is non-authoritative. A disabled provider is reported as zero calls and zero cost; "
        "no synthetic model lift is claimed.",
    ]
    output = ROOT / "out" / "final_metrics.md"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n")
    print(f"Final metrics: {output}")


if __name__ == "__main__":
    main()
