from enum import StrEnum


class DomainEnum(StrEnum):
    """String enum with stable wire-format values."""


class CaseState(DomainEnum):
    CREATED = "CREATED"
    VALIDATING = "VALIDATING"
    READY_FOR_RECONCILIATION = "READY_FOR_RECONCILIATION"
    DETERMINISTIC_MATCHING = "DETERMINISTIC_MATCHING"
    RECONCILED = "RECONCILED"
    PENDING_WITHIN_SLA = "PENDING_WITHIN_SLA"
    NEEDS_ANALYSIS = "NEEDS_ANALYSIS"
    AI_ANALYSIS_PENDING = "AI_ANALYSIS_PENDING"
    SUGGESTED_FOR_REVIEW = "SUGGESTED_FOR_REVIEW"
    ACTIONABLE_EXCEPTION = "ACTIONABLE_EXCEPTION"
    INVALID_INPUT = "INVALID_INPUT"
    APPROVED_PENDING_VERIFICATION = "APPROVED_PENDING_VERIFICATION"
    REJECTED_SUGGESTION = "REJECTED_SUGGESTION"
    DEFERRED = "DEFERRED"


class DecisionLevel(DomainEnum):
    VERIFIED = "VERIFIED"
    SUGGESTED = "SUGGESTED"
    UNRESOLVED = "UNRESOLVED"
    REJECTED = "REJECTED"


class ExceptionCode(DomainEnum):
    PAYMENT_MISSING_AT_GATEWAY = "PAYMENT_MISSING_AT_GATEWAY"
    PAYMENT_STATUS_CONFLICT = "PAYMENT_STATUS_CONFLICT"
    CAPTURE_NOT_SETTLED = "CAPTURE_NOT_SETTLED"
    SETTLEMENT_OVERDUE = "SETTLEMENT_OVERDUE"
    BANK_CREDIT_MISSING = "BANK_CREDIT_MISSING"
    UNIDENTIFIED_BANK_CREDIT = "UNIDENTIFIED_BANK_CREDIT"
    BANK_REFERENCE_CONFLICT = "BANK_REFERENCE_CONFLICT"
    BANK_CONTROL_TOTAL_FAILED = "BANK_CONTROL_TOTAL_FAILED"
    FEE_VARIANCE = "FEE_VARIANCE"
    TAX_VARIANCE = "TAX_VARIANCE"
    REFUND_UNACCOUNTED = "REFUND_UNACCOUNTED"
    CHARGEBACK_UNACCOUNTED = "CHARGEBACK_UNACCOUNTED"
    RESERVE_MOVEMENT_UNACCOUNTED = "RESERVE_MOVEMENT_UNACCOUNTED"
    UNEXPLAINED_RESIDUAL = "UNEXPLAINED_RESIDUAL"
    REFERENCE_CONFLICT = "REFERENCE_CONFLICT"
    AMBIGUOUS_CANDIDATES = "AMBIGUOUS_CANDIDATES"
    DUPLICATE_SOURCE_RECORD = "DUPLICATE_SOURCE_RECORD"
    DOUBLE_ALLOCATION_ATTEMPT = "DOUBLE_ALLOCATION_ATTEMPT"
    CURRENCY_MISMATCH = "CURRENCY_MISMATCH"
    DATE_OUTSIDE_POLICY = "DATE_OUTSIDE_POLICY"
    MALFORMED_INPUT = "MALFORMED_INPUT"
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
    UNSUPPORTED_RECORD_TYPE = "UNSUPPORTED_RECORD_TYPE"


class ExceptionSeverity(DomainEnum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class ComponentType(DomainEnum):
    PAYMENT = "PAYMENT"
    GATEWAY_FEE = "GATEWAY_FEE"
    TAX_ON_FEE = "TAX_ON_FEE"
    REFUND = "REFUND"
    CHARGEBACK = "CHARGEBACK"
    CHARGEBACK_REVERSAL = "CHARGEBACK_REVERSAL"
    RESERVE_HOLD = "RESERVE_HOLD"
    RESERVE_RELEASE = "RESERVE_RELEASE"
    OTHER_DECLARED_ADJUSTMENT = "OTHER_DECLARED_ADJUSTMENT"


class Direction(DomainEnum):
    CREDIT = "CREDIT"
    DEBIT = "DEBIT"


class IngestionQuality(DomainEnum):
    VALID = "VALID"
    PARTIAL = "PARTIAL"
    INVALID = "INVALID"


class FollowUpTaskType(DomainEnum):
    RECHECK_AFTER_SLA = "RECHECK_AFTER_SLA"
    REQUEST_GATEWAY_REPORT = "REQUEST_GATEWAY_REPORT"
    RAISE_BANK_TRACE = "RAISE_BANK_TRACE"
    REVIEW_FEE_POLICY = "REVIEW_FEE_POLICY"
    INVESTIGATE_DUPLICATE = "INVESTIGATE_DUPLICATE"
    MANUAL_EVIDENCE_REVIEW = "MANUAL_EVIDENCE_REVIEW"


class ActorType(DomainEnum):
    SYSTEM = "SYSTEM"
    AI_SUGGESTION = "AI_SUGGESTION"
    HUMAN = "HUMAN"


class CashBucket(DomainEnum):
    BANK_CONFIRMED = "BANK_CONFIRMED"
    SETTLEMENT_CONFIRMED_IN_TRANSIT = "SETTLEMENT_CONFIRMED_IN_TRANSIT"
    EXPECTED_SETTLEMENT = "EXPECTED_SETTLEMENT"
    AT_RISK = "AT_RISK"
    UNRESOLVED = "UNRESOLVED"
