from __future__ import annotations

from pathlib import Path

from services.cash_position.tax_audit import calculate_tax_audit
from services.normalization.policy import load_policy
from services.reconciliation.orchestrator import run_reconciliation

ROOT = Path(__file__).resolve().parents[2]


def _demo_reconciliation():
    data = ROOT / "data" / "demo"
    sources = {
        "orders": str(data / "orders.csv"),
        "payments": str(data / "payments.csv"),
        "settlements": str(data / "settlements.csv"),
        "settlement_components": str(data / "settlement_components.csv"),
        "bank_transactions": str(data / "bank_transactions.csv"),
    }
    policy = load_policy(ROOT / "policies" / "settlement_policy.v1.json")
    return run_reconciliation(sources, policy, "test"), policy


def test_tax_audit_reconciles_mdr_fee_and_gst() -> None:
    result, policy = _demo_reconciliation()
    audit = calculate_tax_audit(result.cases, policy=policy)

    assert audit.total_cases_audited == len(result.cases)
    assert audit.gross_payment_volume_paise > 0
    assert audit.total_gateway_fee_paise > 0
    assert audit.total_tax_paise > 0

    # Total tax must equal claimable ITC plus disputed tax
    assert audit.total_tax_paise == audit.claimable_itc_paise + audit.disputed_tax_paise
    assert audit.itc_status == "DISCREPANCY_FLAGGED"


def test_tax_audit_identifies_all_fee_tax_variances() -> None:
    result, policy = _demo_reconciliation()
    audit = calculate_tax_audit(result.cases, policy=policy)

    discrepancy_case_ids = {item.case_id for item in audit.discrepancies}
    # All 4 fee/tax variance cases generated by the synthetic pipeline must be caught
    expected_variance_cases = {"CASE_FV0056", "CASE_FV0057", "CASE_FV0058", "CASE_FV0059"}
    assert expected_variance_cases.issubset(discrepancy_case_ids)

    fv56 = next(item for item in audit.discrepancies if item.case_id == "CASE_FV0056")
    # Expected fee: 9366, actual fee: 10156 -> variance: +790 paise
    assert fv56.expected_fee_paise == 9366
    assert fv56.actual_fee_paise == 10156
    assert fv56.fee_variance_paise == 790

    # Expected tax: 1685, actual tax: 1828 -> variance: +143 paise
    assert fv56.expected_tax_paise == 1685
    assert fv56.actual_tax_paise == 1828
    assert fv56.tax_variance_paise == 143


def test_tax_audit_handles_empty_cases() -> None:
    audit = calculate_tax_audit([])
    assert audit.total_cases_audited == 0
    assert audit.gross_payment_volume_paise == 0
    assert audit.total_gateway_fee_paise == 0
    assert audit.total_tax_paise == 0
    assert audit.claimable_itc_paise == 0
    assert audit.tax_policy_pass_rate == 1.0
    assert audit.itc_status == "AUDIT_READY"
