from __future__ import annotations

from pathlib import Path

from services.cash_position.tax_audit import calculate_tax_audit
from services.normalization.policy import load_policy
from services.reconciliation.orchestrator import run_reconciliation

ROOT = Path(__file__).resolve().parents[2]


def _demo_reconciliation():
    data = ROOT / "data" / "demo"
    sources = {
        "orders": str(data / "orders.csv"),
        "payments": str(data / "payments.csv"),
        "settlements": str(data / "settlements.csv"),
        "settlement_components": str(data / "settlement_components.csv"),
        "bank_transactions": str(data / "bank_transactions.csv"),
    }
    policy = load_policy(ROOT / "policies" / "settlement_policy.v1.json")
    return run_reconciliation(sources, policy, "test"), policy


def test_tax_audit_reconciles_mdr_fee_and_gst() -> None:
    result, policy = _demo_reconciliation()
    audit = calculate_tax_audit(result.cases, policy=policy)

    assert audit.total_cases_audited == len(result.cases)
    assert audit.gross_payment_volume_paise > 0
    assert audit.total_gateway_fee_paise > 0
    assert audit.total_tax_paise > 0

    # This input can verify recorded fee/tax arithmetic, but cannot prove ITC.
    assert audit.total_tax_paise == audit.supported_tax_paise + audit.disputed_tax_paise
    assert audit.claimable_itc_paise is None
    assert audit.external_tax_statement_available is False
    assert audit.evidence_status == "POLICY_ARITHMETIC_ONLY"
    assert audit.itc_status == "UNAVAILABLE"
    assert audit.policy_id == policy.policy_id
    assert audit.policy_version == policy.version


def test_tax_audit_identifies_all_fee_tax_variances() -> None:
    result, policy = _demo_reconciliation()
    audit = calculate_tax_audit(result.cases, policy=policy)

    discrepancy_case_ids = {item.case_id for item in audit.discrepancies}
    # All 4 fee/tax variance cases generated by the synthetic pipeline must be caught
    expected_variance_cases = {"CASE_FV0056", "CASE_FV0057", "CASE_FV0058", "CASE_FV0059"}
    assert expected_variance_cases.issubset(discrepancy_case_ids)

    fv56 = next(item for item in audit.discrepancies if item.case_id == "CASE_FV0056")
    # Expected fee: 9366, actual fee: 10156 -> variance: +790 paise
    assert fv56.expected_fee_paise == 9366
    assert fv56.actual_fee_paise == 10156
    assert fv56.fee_variance_paise == 790

    # Expected tax: 1685, actual tax: 1828 -> variance: +143 paise
    assert fv56.expected_tax_paise == 1685
    assert fv56.actual_tax_paise == 1828
    assert fv56.tax_variance_paise == 143


def test_tax_audit_handles_empty_cases() -> None:
    audit = calculate_tax_audit([])
    assert audit.total_cases_audited == 0
    assert audit.gross_payment_volume_paise == 0
    assert audit.total_gateway_fee_paise == 0
    assert audit.total_tax_paise == 0
    assert audit.claimable_itc_paise is None
    assert audit.tax_policy_pass_rate is None
    assert audit.fee_policy_pass_rate is None
    assert audit.consistency_status == "NOT_EVALUATED"
    assert audit.itc_status == "UNAVAILABLE"


def test_tax_audit_flags_components_without_a_source_payment() -> None:
    audit = calculate_tax_audit(
        [
            {
                "case_id": "CASE_ORPHAN_COMPONENT",
                "exception_code": "MISSING_PAYMENT",
                "record_snapshot": [
                    {
                        "source_type": "payments",
                        "payment_id": "pay_present",
                        "amount_paise": 10_000,
                    },
                    {
                        "source_type": "settlement_components",
                        "settlement_id": "set_1",
                        "source_event_id": "pay_present",
                        "component_type": "GATEWAY_FEE",
                        "amount_paise": 200,
                    },
                    {
                        "source_type": "settlement_components",
                        "settlement_id": "set_1",
                        "source_event_id": "pay_present",
                        "component_type": "TAX_ON_FEE",
                        "amount_paise": 36,
                    },
                    {
                        "source_type": "settlement_components",
                        "settlement_id": "set_1",
                        "source_event_id": "pay_missing",
                        "component_type": "GATEWAY_FEE",
                        "amount_paise": 50,
                    },
                    {
                        "source_type": "settlement_components",
                        "settlement_id": "set_1",
                        "source_event_id": "pay_missing",
                        "component_type": "TAX_ON_FEE",
                        "amount_paise": 9,
                    },
                ],
            }
        ]
    )

    assert audit.unmatched_component_count == 2
    assert audit.fee_policy_pass_rate == 0.5
    assert audit.tax_policy_pass_rate == 0.5
    assert audit.consistency_status == "DISCREPANCY_FLAGGED"
    assert audit.discrepant_case_count == 1
    assert audit.fee_variance_paise == 50
    assert audit.tax_variance_paise == 9
    assert audit.disputed_tax_paise == 9

    orphan = next(
        item for item in audit.discrepancies if item.discrepancy_code == "SOURCE_EVENT_NOT_FOUND"
    )
    assert orphan.payment_id == "pay_missing"
    assert orphan.settlement_id == "set_1"
    assert orphan.gross_amount_paise == 0
    assert orphan.expected_fee_paise == 0
    assert orphan.actual_fee_paise == 50
    assert orphan.expected_tax_paise == 0
    assert orphan.actual_tax_paise == 9
